### ISSUE TITLE
Repeatable Fields Issue

### ISSUE THREAD

**Issue by saggiatoreblue** [WebDevStudios/Custom-Metaboxes-and-Fields-for-WordPress#557]
Can't add repeatable fields within a group in the latest release. Trying to add a field gives me this error TypeError: $self.data(...) is undefined, this is occurring in cmb.js on line 286.

**Comment by dhenriet** [comment]
When I click on "add row" I still have the bug (Cannot read property 'replace' of undefined), 
- wordpress 4.3.1
- Custom-Metaboxes-and-Fields-for-WordPress 1.2.0

```php
array(
	'name' => __( 'oEmbed', 'cmb' ),
	'desc' => __( 'Enter a youtube, twitter, or instagram URL. Supports services listed at <a href="http://codex.wordpress.org/Embeds">http://codex.wordpress.org/Embeds</a>.', 'cmb' ),
	'id'   => $prefix . 'test_embed',
	'type' => 'oembed',
    'repeatable' => true,               
),

```

![screenshot_2](https://cloud.githubusercontent.com/assets/4640027/10558398/580c796c-74cd-11e5-9991-4668c93902fd.png)

**Comment by tnorthcutt** [comment]
@dhenriet Note that this repo is deprecated; all future development is on [CMB2](https://github.com/WebDevStudios/CMB2) as per the [readme](https://github.com/WebDevStudios/Custom-Metaboxes-and-Fields-for-WordPress/blob/master/readme.md).
