### ISSUE TITLE
Shortcodes in wysiwyg?

### ISSUE THREAD

**Issue by ladybitsdev** [WebDevStudios/Custom-Metaboxes-and-Fields-for-WordPress#732]
Is there a way to make the editors parse a shortcode from another plugin?

**Comment by joshuadavidnelson** [comment]
Don't know if you figured it out, but you'd just need to apply a filter to your output, like [this](https://gist.github.com/joshuadavidnelson/334da35b5ef7e345d51a).

**Comment by ladybitsdev** [comment]
I did figure it out but thank you!
