### ISSUE TITLE
Adding filter for text_domain

### ISSUE THREAD

**Issue by wpexplorer** [WebDevStudios/Custom-Metaboxes-and-Fields-for-WordPress#766]
Would be nice to be able to alter the text_domain via a filter since most cases the class will be added inside a plugin or a theme it would be good to switch out the text_domain so it can be translated.

Thanks!

**Comment by tnorthcutt** [comment]
@wpexplorer Note that this repo is deprecated; all future development is on [CMB2](https://github.com/WebDevStudios/CMB2) as per the [readme](https://github.com/WebDevStudios/Custom-Metaboxes-and-Fields-for-WordPress/blob/master/readme.md).
